// testWord.js
const questionNumber = document.getElementById('question-number');
const question = document.getElementById('question');
const optionsContainer = document.getElementById('options-container');

const startEngQuizBtn = document.getElementById('engQuiz');
const startKorQuizBtn = document.getElementById('korQuiz');
const endQuizBtn = document.getElementById('endQuiz');

const quizContainer = document.getElementById('quiz-container');

const resultContainer = document.getElementById('result-container');
const resultText = document.getElementById('result-text');
const restartBtn = document.getElementById('restart-btn');
const wrongWordBtn = document.getElementById('wrongWord-btn');

// '단어 찾아보기' 버튼과 입력 필드, 결과 표시 영역을 찾는다.
const searchWordBtn = document.getElementById('searchWord-btn');
const searchWordInput = document.getElementById('searchWord-input');
const searchWordResult = document.getElementById('searchWord-result');


const wordList = [
  { eng: 'extention', kor: '확대' },
  { eng: 'phase', kor: '단계적으로 시행하다' },
  { eng: 'irrelevant', kor: '관계가 없는, 부적절한' },
  { eng: 'obliterate', kor: '지우다' },
  { eng: 'empirical', kor: '경험적인' },
  { eng: 'incorporate', kor: '포함하다' },
  { eng: 'inordinate', kor: '과도한' },
  { eng: 'lavish', kor: '넉넉한' },
  { eng: 'equivocal', kor: '애매한' },
  { eng: 'revelation', kor: '폭로' },
  { eng: 'antecedent', kor: '앞서는, 전례' },
  { eng: 'affection', kor: '애정' },
  { eng: 'clarify', kor: '분명히 하다' },
  { eng: 'noxious', kor: '유해한' },
  { eng: 'innocuous', kor: '무해한' },
  { eng: 'perturb', kor: '혼란시키다' },
  { eng: 'assimilate', kor: '동화시키다' },
  { eng: 'exalt', kor: '칭찬하다' },
  { eng: 'compliment', kor: '칭찬하다' },
  { eng: 'deride', kor: '비웃다' },
  { eng: 'risible', kor: '우스운' },
  { eng: 'sanction', kor: '허가, 비준' },
  { eng: 'align', kor: '정렬하다' },
  { eng: 'disparage', kor: '경시하다' },
  { eng: 'regnant', kor: '지배하는' },
  { eng: 'obdurate', kor: '고집센' },
  { eng: 'reciprocal', kor: '상호간의' },
  { eng: 'desolate', kor: '고독한' },
  { eng: 'cursory', kor: '피상적인' },
  { eng: 'lapse', kor: '쇠퇴, 경과' },
  { eng: 'elapse', kor: '경과하다' },
  { eng: 'insulate', kor: '절연, 고립' },
  { eng: 'convene', kor: '소집하다' },
  { eng: 'extricate', kor: '풀어주다' },
  { eng: 'resurge', kor: '되살아나다' },
  { eng: 'crudity', kor: '조잡함' },
  { eng: 'dispense with', kor: '~없이 살다' },
  { eng: 'equanimous', kor: '침착한' },
  { eng: 'mobilize', kor: '동원하다' },
  { eng: 'explicit', kor: '명백한' },
  { eng: 'implicit', kor: '함축적인, 내포된, 암묵의' },
  { eng: 'negate', kor: '부정하다' },
  { eng: 'neglect', kor: '무시하다' },
  { eng: 'ineffable', kor: '말로 표현할 수 없는' },
  { eng: 'persevere', kor: '버티어내다' },
  { eng: 'sever', kor: '절단하다' },
  { eng: 'interminable', kor: '끝없는' },
  { eng: 'abstrain', kor: '삼가다' },
  { eng: 'confer', kor: '상의하다' },
  { eng: 'sparse', kor: '부족한' },
  { eng: 'flagrant', kor: '노골적인, 악명높은' },
  { eng: 'protrude', kor: '튀어나오다' },
  { eng: 'extrude', kor: '밀어내다' },
  { eng: 'obstrude', kor: '끼어들다' },
  { eng: 'relocate', kor: '이동하다' },
  { eng: 'ally', kor: '동맹, 결합하다' },
  { eng: 'alley', kor: '골목' },
  { eng: 'affable', kor: '상냥한' },
  { eng: 'arrogate', kor: '사칭하다' },
  { eng: 'interrogate', kor: '심문하다' },
  { eng: 'ascertain', kor: '확인하다' },
  { eng: 'denominate', kor: '명명하다' },
  { eng: 'solidarize', kor: '단결하다' },
  { eng: 'expedite', kor: '촉진하다' },
  { eng: 'ambivalent', kor: '반대 감정이 병존하는' },
  { eng: 'ambience', kor: '주위, 분위기' },
  { eng: 'approbate', kor: '인정하다, 승인하다' },
  { eng: 'disclaim', kor: '말하다, 권리를 포기하다, 부인하다' },
  { eng: 'germane', kor: '밀접한 관계가 있는' },
  { eng: 'congenital', kor: '선천적인' },
  { eng: 'conciliate', kor: '달래다' },
  { eng: 'intermission', kor: '중지, 휴식' },
  { eng: 'compatible', kor: '양립할 수 있는' },
  { eng: 'conduce', kor: '공헌하다' },
  { eng: 'evict', kor: '쫓아내다' },
  { eng: 'fraught', kor: '가득한, 걱정하는' },
  { eng: 'ingratiate', kor: '환심을 사다' },
  { eng: 'precipitate', kor: '침전하다' },
  { eng: 'conspicuous', kor: '눈에 잘 띄는' },
  { eng: 'inflict', kor: '가하다' },
  { eng: 'acquit', kor: '무죄를 선고하다' },
  { eng: 'reproach', kor: '비난하다' },
  { eng: 'swerve', kor: '벗어나다' },
  { eng: 'hypnotize', kor: '최면을 걸다' },
  { eng: 'predispose', kor: '~하는 경향을 갖도록 하다' },
  { eng: 'erode', kor: '약화시키다' },
  { eng: 'depreciate', kor: '가치가 떨어지다' },
  { eng: 'feasible', kor: '실행 가능한' },
  { eng: 'viable', kor: '독자 생존 가능한' },
  { eng: 'dubious', kor: '수상쩍은' },
  { eng: 'distate', kor: '혐오감' },
  { eng: 'surmise', kor: '추측하다' },
  { eng: 'susceptible', kor: '민감한' },
  { eng: 'susceptive', kor: '감수성이 풍부한' },
  { eng: 'prone', kor: '~하기 쉬운' },
  { eng: 'peripheral', kor: '지엽적인' },
  { eng: 'cajole', kor: '꼬드기다' },
  { eng: 'callow', kor: '미숙한' },
  { eng: 'capitulate', kor: '굴복하다' },
  { eng: 'repudiate', kor: '비난하다' },
  { eng: 'renounce', kor: '포기하다' },
  { eng: 'denounce', kor: '맹렬히 비난하다' },
  { eng: 'deplore', kor: '한탄하다' },
  { eng: 'deprecate', kor: '반대하다' },
  { eng: 'demur', kor: '이의를 제기하다' },
  { eng: 'desultory', kor: '두서없는' },
  { eng: 'diffident', kor: '조심스러운, 소심한' },
  { eng: 'deleterious', kor: '해로운' },
  { eng: 'pernicious', kor: '치명적인' },
  { eng: 'belie', kor: '거짓임을 보여주다' },
  { eng: 'perfidy', kor: '배신' },
  { eng: 'treachery', kor: '배신' },
  { eng: 'treacherous', kor: '기만적인' },
  { eng: 'ostentatious', kor: '호사스러운' },
  { eng: 'penchant', kor: '애호' },
  { eng: 'peremptory', kor: '위압적인' },
  { eng: 'frugal', kor: '소박한' },
  { eng: 'thrifty', kor: '절약하는' },
  { eng: 'parsimonious', kor: '인색한' },
  { eng: 'penurious', kor: '몹시 가난한' },
  { eng: 'destitute', kor: '극빈한' },
  { eng: 'penniless', kor: '무일푼의' },
  { eng: 'impassive', kor: '무표정한' },
  { eng: 'imperturbable', kor: '쉽게 동요하지 않는' },
  { eng: 'implacable', kor: '확고한' },
  { eng: 'inexorable', kor: '거침없는' },
  { eng: 'inept', kor: '솜씨없는' },
  { eng: 'insolent', kor: '버릇없는' },
  { eng: 'haughty', kor: '거만한' },
  { eng: 'impudent', kor: '무례하는' },
  { eng: 'imprudent', kor: '경솔한' },
  { eng: 'impetuous', kor: '성급한' },
  { eng: 'impugn', kor: '의심하다' },
  { eng: 'phlegmatic', kor: '침착한' },
  { eng: 'petulant', kor: '심술을 부리는' },
  { eng: 'platitude', kor: '진부한 이야기, 평범한' },
  { eng: 'prosaic', kor: '평범한, 따분한' },
  { eng: 'prodigious', kor: '엄청난' },
  { eng: 'bask', kor: '햇살을 쬐다' },
  { eng: 'rein', kor: '고삐, 통솔권' },
  { eng: 'monarch', kor: '군주' },
  { eng: 'exile', kor: '망명, 추방' },
  { eng: 'banish', kor: '추방하다' },
  { eng: 'exert', kor: '노력하다, 행사하다' },
  { eng: 'abide', kor: '깃들다' },
  { eng: 'abhor', kor: '혐오하다' },
  { eng: 'loathe', kor: '혐오하다' },
  { eng: 'loath', kor: '~하기를 꺼리는' },
  { eng: 'ludicrous', kor: '터무니 없는' },
  { eng: 'scramble', kor: '재빨리 움직이다, 발진, 앞다투다' },
  { eng: 'mundane', kor: '재미없는, 평범한' },
  { eng: 'inundate', kor: '범람하다' },
  { eng: 'lexicon', kor: '어휘' },
  { eng: 'semblance', kor: '외관' },
  { eng: 'pertinent', kor: '적절한' },
  { eng: 'preclude', kor: '못하게 하다' },
  { eng: 'precarious', kor: '불안정한' },
  { eng: 'lucrative', kor: '수익성이 좋은' },
  { eng: 'imperative', kor: '반드시 해야하는, 위엄있는' },
  { eng: 'plummet', kor: '곤두박질치다' },
  { eng: 'plunge', kor: '거꾸러지다' },
  { eng: 'recession', kor: '불황' },
  { eng: 'revenue', kor: '수익' },
  { eng: 'fiscal', kor: '국가제정' },
  { eng: 'expenditure', kor: '지출' },
  { eng: 'expend', kor: '노력을 쏟다' },
  { eng: 'deficit', kor: '적자' },
  { eng: 'pecuniary', kor: '금전상의' },
  { eng: 'sumptuous', kor: '호화로운' },
  { eng: 'supercilious', kor: '거만한' },
  { eng: 'impervious', kor: '불침투성의' },
  { eng: 'pervious', kor: '통과시키는' },
  { eng: 'permeable', kor: '스며들 수 있는' },
  { eng: 'electrocute', kor: '감전사시키다' },
  { eng: 'convex', kor: '볼록한' },
  { eng: 'concave', kor: '오목한' },
  { eng: 'diverge', kor: '갈라지다' },
  { eng: 'divergence', kor: '발산' },
  { eng: 'overhang', kor: '돌출하다' },
  { eng: 'prospective', kor: '유망한' },
  { eng: 'prospect', kor: '가망, 탐사하다' },
  { eng: 'promising', kor: '유망한' },
  { eng: 'overall', kor: '전반적인' },
  { eng: 'component', kor: '요소, 부품' },
  { eng: 'debilitated', kor: '심신이 약해진' },
  { eng: 'promote', kor: '촉진하다' },
  { eng: 'desireable', kor: '바람직한' },
  { eng: 'benevolent', kor: '인정많다' },
  { eng: 'discourage', kor: '좌절시키다' },
  { eng: 'diverse', kor: '다양한' },
  { eng: 'sequential', kor: '순차적인' },
  { eng: 'mutter', kor: '중얼거리다' },
  { eng: 'pinpoint', kor: '찾아내다' },
  { eng: 'tortuous', kor: '길고 복잡한' },
  { eng: 'torturous', kor: '고통스러운' },
  { eng: 'pole', kor: '여론조사' },
  { eng: 'adapt', kor: '적응하다, 조정하다' },
  { eng: 'adopt', kor: '입양하다, 채택하다' },
  { eng: 'defiantly', kor: '반항적으로' },
  { eng: 'berth', kor: '침상' },
  { eng: 'complacent', kor: '현실에 안주하는' },
  { eng: 'complaisant', kor: '선뜻 남의 말을 듣는, 고분고분한, 순종적인' },
  { eng: 'disinterested', kor: '사심이 없는' },
  { eng: 'counsel', kor: '조언' },
  { eng: 'drown', kor: '익사하다' },
  { eng: 'drawn', kor: '핼쑥한' },
  { eng: 'personnel', kor: '인원' },
  { eng: 'envelop', kor: '감싸다' },
  { eng: 'envelope', kor: '봉투' },
  { eng: 'averse', kor: '~을 싫어하는' },
  { eng: 'adverse', kor: '불리한' },
  { eng: 'appraise', kor: '평가하다' },
  { eng: 'apprise', kor: '알리다' },
  { eng: 'breach', kor: '위반' },
  { eng: 'hoard', kor: '비축물' },
  { eng: 'horde', kor: '군중' },
  { eng: 'discrete', kor: '별개의' },
  { eng: 'discreet', kor: '신중한' },
  { eng: 'broach', kor: '이야기를 꺼내다' },
  { eng: 'lag', kor: '뒤쳐지다' },
  { eng: 'entitle', kor: '제목을 붙이다' },
  { eng: 'disseminate', kor: '퍼뜨리다' },
  { eng: 'denigrate', kor: '폄하하다' },
  { eng: 'deploy', kor: '배치하다' },
  { eng: 'increment', kor: '증가' },
  { eng: 'commensurate', kor: '상응하는' },
  { eng: 'disperse', kor: '흩어지다' },
  { eng: 'dissipate', kor: '소멸되다' },
  { eng: 'proactive', kor: '선조치하는' },
  { eng: 'predation', kor: '포식' },
  { eng: 'bombastic', kor: '과장한' },
  { eng: 'brazen', kor: '뻔뻔한' },
  { eng: 'corse', kor: '거친' },
  { eng: 'draught', kor: '찬바람' },
  { eng: 'drought', kor: '가뭄' },
  { eng: 'over budget', kor: '예산 초과' },
  { eng: 'complement', kor: '보안하다' },
  { eng: 'proscribe', kor: '금하다' },
  { eng: 'balmy', kor: '아늑한' },
  { eng: 'barmy', kor: '약간 제정신이 아닌' },
  { eng: 'bough', kor: '가지' },
  { eng: 'militate', kor: '작용하다' },
  { eng: 'mitigate', kor: '완화시키다' },
  { eng: 'flout', kor: '어기다' },
  { eng: 'flaunt', kor: '과시하다' },
  { eng: 'altogether', kor: '완전히' },
  { eng: 'peddle', kor: '팔러 다니다' },
  { eng: 'wreathe', kor: '둘러싸다' },
  { eng: 'wreath', kor: '화환' },
  { eng: 'principal', kor: '주요한' },
  { eng: 'statute', kor: '법규' },
  { eng: 'palate', kor: '구개' },
  { eng: 'sceptic', kor: '회의론자' },
  { eng: 'canvass', kor: '유세를 하다' },
  { eng: 'pat', kor: '쓰다듬다' },
  { eng: 'doze', kor: '잠이 들다' },
  { eng: 'grime', kor: '때' },
  { eng: 'grim', kor: '엄숙한' },
  { eng: 'grimy', kor: '더러운' },
  { eng: 'derelict', kor: '버려진, 유기된' },
  { eng: 'dilate', kor: '확장하다' },
  { eng: 'contrive', kor: '고안하다' },
  { eng: 'contrivance', kor: '억지로 짜맞춘 것, 장치' },
  { eng: 'conjure', kor: '마술을 하다' },
  { eng: 'disrupt', kor: '방해하다' },
  { eng: 'distract', kor: '주의를 산만하게 하다' },
  { eng: 'detract', kor: '주의를 딴데로 돌리다' },
  { eng: 'dilapidated', kor: '다 허물어져가는' },
  { eng: 'ramshackle', kor: '곧 무너질 것같은' },
  { eng: 'diatribe', kor: '비판' },
  { eng: 'tirade', kor: '장황한 비난' },
  { eng: 'harangue', kor: '장광설을 늘어놓다' },
  { eng: 'harbinger', kor: '전조' },
  { eng: 'hermetic', kor: '밀폐된' },
  { eng: 'hapless', kor: '불운한' },
  { eng: 'guile', kor: '간교한 속임수' },
  { eng: 'loquacious', kor: '말이 많은' },
  { eng: 'garrulous', kor: '수다스러운' },
  { eng: 'taciturn', kor: '과묵한' },
  { eng: 'laconic', kor: '말을 많이 하지 않는' },
  { eng: 'irascrible', kor: '화를 잘 내는' },
  { eng: 'inveterate', kor: '상습적인' },
  { eng: 'interpid', kor: '용감무쌍한' },
  { eng: 'audacious', kor: '대담한' },
  { eng: 'audacity', kor: '뻔뻔함' },
  { eng: 'austere', kor: '소박한, 금욕적인' },
  { eng: 'austerity', kor: '내핍상태' },
  { eng: 'ascetic', kor: '금욕적인' },
  { eng: 'banal', kor: '진부한, 시시한' },
  { eng: 'hankneyed', kor: '진부한' },
  { eng: 'beguile', kor: '구슬리다' },
  { eng: 'belittle', kor: '하찮게 만들다' },
  { eng: 'belligerant', kor: '적대적인' },
  { eng: 'blatant', kor: '노골적인' },
  { eng: 'blight', kor: '망치다, 병충해' },
  { eng: 'blithe', kor: '태평스러운' },
  { eng: 'bolster', kor: '북돋우다' },
  { eng: 'novice', kor: '초심자' },
  { eng: 'proficiency', kor: '능숙함' },
  { eng: 'niche', kor: '틈새' },
  { eng: 'enlist', kor: '입대하다' },
  { eng: 'frivolous', kor: '경솔한' },
  { eng: 'atypical', kor: '이례적인' },
  { eng: 'haphazard', kor: '무계획적으로' },
  { eng: 'fervent', kor: '열렬한' },
  { eng: 'ardent', kor: '열렬한' },
  { eng: 'transitory', kor: '일시적인' },
  { eng: 'transient', kor: '일시적인' },
  { eng: 'ephemeral', kor: '수명이 짧은' },
  { eng: 'defy', kor: '반항하다' },
  { eng: 'verbose', kor: '장황한' },
  { eng: 'terse', kor: '간결한' },
  { eng: 'workforce', kor: '노동력' },
  { eng: 'drastically', kor: '철저한, 대폭적으로' },
  { eng: 'widerness', kor: '야생' },
  { eng: 'acoustically', kor: '음향적으로' },
  { eng: 'rigid', kor: '경직된' },
  { eng: 'statistical', kor: '통계에 근거한' },
  { eng: 'undue', kor: '과도한' },
  { eng: 'fuzzy', kor: '흐릿한' },
  { eng: 'apprehensive', kor: '걱정되는' },
  { eng: 'abortive', kor: '무산된, 유산된' },
  { eng: 'apt', kor: '적절한' },
  { eng: 'aptitude', kor: '소질, 적성' },
  { eng: 'tumid', kor: '부어오른, 과장된' },
  { eng: 'travesty', kor: '졸렬한 모방, 희화화' },
  { eng: 'defuse', kor: '진정시키다' },
  { eng: 'degenerate', kor: '악화되다' },
  { eng: 'castigate', kor: '책망하다' },
  { eng: 'chastise', kor: '꾸짖다' },
  { eng: 'rebuke', kor: '꾸짖다' },
  { eng: 'chide', kor: '꾸짖다' },
  { eng: 'censure', kor: '질책하다' },
  { eng: 'reprimand', kor: '질책하다' },
  { eng: 'convoke', kor: '소집하다' },
  { eng: 'corroborate', kor: '확증하다' },
  { eng: 'conjecture', kor: '추측' },
  { eng: 'culminate', kor: '극에 이르다' },
  { eng: 'peculiarity', kor: '기이한 특징, 특성' },
  { eng: 'contention', kor: '논쟁, 주장' },
  { eng: 'diaphanous', kor: '속이 비치는' },
  { eng: 'iconoclast', kor: '우상파괴자' },
  { eng: 'idyllic', kor: '목가적인, 전원적인' },
  { eng: 'ingenuous', kor: '순진한' },
  { eng: 'naive', kor: '순진한' },
  { eng: 'disingenuous', kor: '부정직한, 표리부동한' },
  { eng: 'esoteric', kor: '난해한' },
  { eng: 'abstruse', kor: '난해한' },
  { eng: 'abject', kor: '비참한' },
  { eng: 'abrogate', kor: '폐지하다' },
  { eng: 'abjure', kor: '포기하다' },
  { eng: 'abscond', kor: '종적을 감추다' },
  { eng: 'abdicate', kor: '퇴위하다' },
  { eng: 'absolve', kor: '용서하다' },
  { eng: 'abstain', kor: '삼가다' },
  { eng: 'abrige', kor: '요약하다' },
  { eng: 'acquiesce', kor: '묵종하다' },
  { eng: 'amicable', kor: '우호적인' },
  { eng: 'aloof', kor: '냉담한' },
  { eng: 'ameliorate', kor: '개선하다' },
  { eng: 'amenable', kor: '고분고분한' },
  { eng: 'exacerbate', kor: '악화시키다' },
  { eng: 'alacrity', kor: '민첩함' },
  { eng: 'acrimonious', kor: '신랄한' },
  { eng: 'accolade', kor: '포상, 수상' },
  { eng: 'accost', kor: '위협적으로 다가가 말을 걸다' },
  { eng: 'acerbic', kor: '신랄한' },
  { eng: 'acute', kor: '급성의' },
  { eng: 'acrid', kor: '매캐한' },
  { eng: 'abate', kor: '약해지다, 수그러지다' },
  { eng: 'abet', kor: '방조하다' },
  { eng: 'accede', kor: '응하다' },
  { eng: 'accession', kor: '취임, 가입' },
  { eng: 'abash', kor: '무안하게 하다' },
  { eng: 'abeyance', kor: '중지' },
  { eng: 'absteminous', kor: '자제하는' },
  { eng: 'abnegate', kor: '버리다' },
  { eng: 'abbreviate', kor: '축약하다' },
  { eng: 'refrain', kor: '삼가다' },
  { eng: 'comply', kor: '따르다' },
  { eng: 'conform', kor: '따르다' },
  { eng: 'clemency', kor: '관용, 관대한 처분' },
  { eng: 'circumspect', kor: '신중한' },
  { eng: 'prudent', kor: '신중한' },
  { eng: 'erudite', kor: '박학다식한' },
  { eng: 'eschew', kor: '삼가다' },
  { eng: 'emulate', kor: '본받다' },
  { eng: 'eclectic', kor: '폭넓은, 다방면에 걸친' },
  { eng: 'edify', kor: '고양시키다' },
  { eng: 'enervate', kor: '기력을 떨어뜨리다' },
  { eng: 'evanescent', kor: '덧없는, 무상한' },
  { eng: 'fleeting', kor: '순식간의' },
  { eng: 'futile', kor: '헛된' },
  { eng: 'furtive', kor: '은밀한' },
  { eng: 'fatuous', kor: '어리석은' },
  { eng: 'facetious', kor: '경박한' },
  { eng: 'flippant', kor: '경솔한' },
  { eng: 'ominous', kor: '불길한' },
  { eng: 'truculent', kor: '반항적인' },
  { eng: 'delirious', kor: '의식이 혼미한' },
  { eng: 'tumultuous', kor: '격동의' },
  { eng: 'tempestuous', kor: '열렬한' },
  { eng: 'tumult', kor: '소란' },
  { eng: 'turgid', kor: '과장된, 복잡한' },
  { eng: 'commonplace', kor: '평범한' },
  { eng: 'contestant', kor: '참가자' },
  { eng: 'enliven', kor: '생동감 있게 만들다' },
  { eng: 'empathize', kor: '공감하다' },
  { eng: 'emphasize', kor: '강조하다' },
  { eng: 'persuasion', kor: '설득' },
  { eng: 'consensus', kor: '합의' },
  { eng: 'contrary', kor: '반대' },
  { eng: 'discord', kor: '불화' },
  { eng: 'relevence', kor: '적합성, 연관성' },
  { eng: 'quantify', kor: '수량화하다' },
  { eng: 'vivid', kor: '생생한' },
  { eng: 'hardwired', kor: '타고나는, 고유한' },
  { eng: 'disturbing', kor: '불안하게 만드는, 방해가 되는' },
  { eng: 'intriguingly', kor: '흥미를 자아내는, 호기심을 자극하는' },
  { eng: 'obsess', kor: '강박관념을 갖게 하다, 사로잡다' },
  { eng: 'compulsion', kor: '강요' },
  { eng: 'impulse', kor: '충동' },
  { eng: 'resume', kor: '다시 시작하다' },
  { eng: 'foster', kor: '키우다' },
  { eng: 'reside', kor: '살다' },
  { eng: 'nonperishable', kor: '잘 상하지 않는' },
  { eng: 'handy', kor: '편리한, 유용한' },
  { eng: 'heartmelt', kor: '마음에서 우러난' },
  { eng: 'steer', kor: '이끌다' },
  { eng: 'trot', kor: '빨리 걷다' },
  { eng: 'resign', kor: '사임하다' },
  { eng: 'pose', kor: '제기하다' },
  { eng: 'prolificacy', kor: '다산, 다작' },
  { eng: 'punctuate', kor: '구두점을 찍다' },
  { eng: 'stillness', kor: '정적, 고요함' },
  { eng: 'entail', kor: '수반하다' },
  { eng: 'consult', kor: '상의하다' },
  { eng: 'personify', kor: '의인화하다' },
  { eng: 'predominance', kor: '우위' },
  { eng: 'legitimately', kor: '합법적으로' },
  { eng: 'rehabilitate', kor: '복귀시키다, 복구하다' },
  { eng: 'span', kor: '기간, 폭' },
  { eng: 'underlying', kor: '근본적인' },
  { eng: 'deem', kor: '~라고 여기다' },
  { eng: 'fabrication', kor: '구조물, 제조' },
  { eng: 'nobility', kor: '귀족, 고결함' },
  { eng: 'proximity', kor: '근접성' },
  { eng: 'adequately', kor: '적절하게' },
  { eng: 'disposal', kor: '처리' },
  { eng: 'immobilize', kor: '고정시키다' },
  { eng: 'hostility', kor: '적대감' },
  { eng: 'revitalize', kor: '새로운 활력을 주다' },
  { eng: 'preventive', kor: '예방의' },
  { eng: 'straightforward', kor: '솔직한, 정직한' },
  { eng: 'browse', kor: '뜯어먹다, 둘러보다' },
  { eng: 'specify', kor: '명시하다' },
  { eng: 'introductory', kor: '입문의, 도입의' },
  { eng: 'rugged', kor: '울퉁불퉁한' },
  { eng: 'misguided', kor: '오도된' },
  { eng: 'validate', kor: '입증하다' },
  { eng: 'comprise', kor: '차지하다' },
  { eng: 'vowel', kor: '모음' },
  { eng: 'consonant', kor: '자음' },
  { eng: 'fuss', kor: '소란' },
  { eng: 'feat', kor: '재주, 묘기' },
  { eng: 'chunk', kor: '덩어리' },
  { eng: 'burglar', kor: '강도' },
  { eng: 'groom', kor: '손질하다' },
  { eng: 'discrepancy', kor: '차이' },
  { eng: 'plot', kor: '음모하다, 작은 땅, 줄거리' },
  { eng: 'spot', kor: '발견하다' },
  { eng: 'keystone', kor: '핵심' },
  { eng: 'narrative', kor: '이야기' },
  { eng: 'pneumonia', kor: '폐렴' },
  { eng: 'disadvantage', kor: '약점' },
  { eng: 'allotment', kor: '배분' },
  { eng: 'expansive', kor: '광범위한' },
  { eng: 'odds', kor: '역경' },
  { eng: 'harbor', kor: '항구, 피난처' },
  { eng: 'charitable', kor: '자비로운' },
  { eng: 'provision', kor: '제공, 공급' },
  { eng: 'autonomous', kor: '자율적인' },
  { eng: 'forensic', kor: '법의학' },
  { eng: 'pathology', kor: '병리' },
  { eng: 'remorse', kor: '뉘우치는' },
  { eng: 'frankly', kor: '실제로' },
  { eng: 'in terms of', kor: '~와 관하여' },
  { eng: 'allege', kor: '혐의를 제기하다' },
  { eng: 'grudge', kor: '원한' },
  { eng: 'begrudge', kor: '시기하다' },
  { eng: 'forge', kor: '구축하다, 위조하다, 대장간' },
  { eng: 'counterfeit', kor: '위조의' },
  { eng: 'reckon', kor: '~라 생각하다' },
  { eng: 'swarm', kor: '떼, 무리' },
  { eng: 'weep', kor: '울다' },
  { eng: 'blob', kor: '방울' },
  { eng: 'cask', kor: '통' },
  { eng: 'gusto', kor: '열정' },
  { eng: 'expound', kor: '자세히 설명하다' },
  { eng: 'casualty', kor: '사상자' },
  { eng: 'chairperson', kor: '사회자' },
  { eng: 'actuality', kor: '실재, 실제' },
  { eng: 'mere', kor: '겨우 ~의' },
  { eng: 'chime', kor: '울리다, 시간을 알리다' },
  { eng: 'mumble', kor: '웅얼거리다' },
  { eng: 'dense', kor: '빽빽한' },
  { eng: 'florid', kor: '발그레한' },
  { eng: 'recital', kor: '발표회' },
  { eng: 'consuming', kor: '온 마음을 사로잡는' },
  { eng: 'crop', kor: '농작물' },
  { eng: 'brood', kor: '(과거 기억을)곱씹다' },
  { eng: 'possibly', kor: '아마' },
  { eng: 'discolour', kor: '변색되다' },
  { eng: 'dupe', kor: '속이다' },
  { eng: 'exceptional', kor: '특출한' },
  { eng: 'lusty', kor: '건장한' },
  { eng: 'robust', kor: '팔팔한' },
  { eng: 'interfering', kor: '간섭하는' },
  { eng: 'nudge', kor: '팔꿈치로 찌르다' },
  { eng: 'provoke', kor: '유발하다, 도발하다' },
  { eng: 'arguable', kor: '주장할 수 있는' },
  { eng: 'disconcert', kor: '불안하게 하다' },
  { eng: 'fussy', kor: '노심초사하다' },
  { eng: 'intensify', kor: '심해지다, 강화하다' },
  { eng: 'groundless', kor: '근거 없는' },
  { eng: 'pervasive', kor: '만연하는' },
  { eng: 'pervasively', kor: '넘쳐, 충만하게' },
  { eng: 'substantive', kor: '실질적인' },
  { eng: 'kickback', kor: '뇌물, 리베이트(사례금)' },
  { eng: 'graft', kor: '이식하다, 접목하다' },
  { eng: 'fumble', kor: '더듬거리다' },
  { eng: 'stammer', kor: '말을 더듬다' },
  { eng: 'flounder', kor: '허둥대다' },
  { eng: 'sabotage', kor: '방해하다, 파괴하다' },
  { eng: 'dim', kor: '어둑한' },
  { eng: 'solemn', kor: '엄숙한' },
  { eng: 'splendid', kor: '훌륭한' },
  { eng: 'ethereal', kor: '천상의' },
  { eng: 'burlesque', kor: '풍자시' },
  { eng: 'gnaw', kor: '갉아먹다' },
  { eng: 'morsel', kor: '작은 양' },
  { eng: 'taper', kor: '가늘어지다' },
  { eng: 'stale', kor: '신선하지 않은' },
  { eng: 'stalemate, impasse, deadlock', kor: '교착상태' },
  { eng: 'vapid', kor: '멋이 없는' },
  { eng: 'inane', kor: '어리석은' },
  { eng: 'defer', kor: '미루다' },
  { eng: 'deter', kor: '단념시키다' },
  { eng: 'unmet', kor: '충족되지 않는' },
  { eng: 'proliferate', kor: '급증하다, 확산되다' },
  { eng: 'profuse', kor: '많은, 다량의' },
  { eng: 'delineate', kor: '기술하다, 설명하다' },
  { eng: 'inimical', kor: '적대적인' },
  { eng: 'ineluctable', kor: '피할 수 없는' },
  { eng: 'incipient', kor: '막 시작된' },
  { eng: 'as long as', kor: '~하는 한' },
  { eng: 'prodigal', kor: '낭비하는' },
  { eng: 'promulgate', kor: '반포하다, 공포하다' },
  { eng: 'plough', kor: '쟁기' },
  { eng: 'incursion', kor: '습격' },
  { eng: 'incorrigible', kor: '구제불능의' },
  { eng: 'indigent', kor: '궁핍한' },
  { eng: 'indolent', kor: '게으른' },
  { eng: 'incisive', kor: '예리한' },
  { eng: 'bristle', kor: '털을 곤두세우다' },
  { eng: 'viscous', kor: '끈적거리는' },
  { eng: 'flagellum', kor: '편모, 채찍' },
  { eng: 'flicker', kor: '깜박거리다' },
  { eng: 'bioluminscence', kor: '생체발광' },
  { eng: 'burst', kor: '터지다, 파열' },
  { eng: 'beacon', kor: '불빛, 봉화' },
  { eng: 'decoy', kor: '유인, 미끼' },
  { eng: 'jettison', kor: '버리다' },
  { eng: 'camouflage', kor: '위장하다' },
  { eng: 'exhilarte', kor: '기분을 돋우다' },
  { eng: 'exasperate', kor: '화나게 하다' },
  { eng: 'excoriate', kor: '벗겨지게 하다, 박리, 찰과상을 입히다, 혹평하다' },
  { eng: 'exonerate, exculpate', kor: '무죄임을 밝혀주다' },
  { eng: 'docile', kor: '유순한' },
  { eng: 'dormant', kor: '휴면기의' },
  { eng: 'subordinate', kor: '종속된, 부하' },
  { eng: 'subsequent', kor: '그 다음의, 차후의' },
  { eng: 'obedient, submissive', kor: '순종적인' },
  { eng: 'rigorous', kor: '철저한, 엄격한' },
  { eng: 'relinquish', kor: '포기하다' },
  { eng: 'forsake', kor: '버리다, 저버리다' },
  { eng: 'cede', kor: '양도하다' },
  { eng: 'funnel', kor: '깔대기' },
  { eng: 'laborious, onerous, ardous', kor: '힘든' },
  { eng: 'auspicious', kor: '상서로운, 길조의' },
  { eng: 'amiable', kor: '쾌할한' },
  { eng: 'affable, genial', kor: '상냥한' },
  { eng: 'shrewd', kor: '상황 판단이 빠른, 기민한' },
  { eng: 'sagacious', kor: '현명한' },
  { eng: 'salubrious', kor: '살기 좋은' },
  { eng: 'salutary', kor: '유익한' },
  { eng: 'salient', kor: '핵심적인' },
  { eng: 'sanguine, optimistic', kor: '낙관적인' },
  { eng: 'choleric', kor: '화를 잘 내는' },
  { eng: 'reticent', kor: '말을 잘 안 하는' },
  { eng: 'sanctimonious', kor: '독실한 체하는' },
  { eng: 'spurious', kor: '거짓된, 비논리적인' },
  { eng: 'stymie', kor: '방해하다' },
  { eng: 'subjugate', kor: '예속시키다, 정복하다' },
  { eng: 'surreptitious, furtive', kor: '은밀한' },
  { eng: 'superfluous', kor: '불필요한' },
  { eng: 'vigilant, wary', kor: '바짝 경계하는' },
  { eng: 'nimble', kor: '재빠른, 날렵한' },
  { eng: 'innominate', kor: '무명의' },
  { eng: 'vigin', kor: '처녀, 동정녀' },
  { eng: 'annihilate', kor: '전멸시키다, 몰살하다' },
  { eng: 'extirpate', kor: '제거하다, 박멸하다, 근절하다' },
  { eng: 'impunity', kor: '처벌을 받지 않음' },
  { eng: 'impregnable', kor: '철벽의, 난공불락의' },
  { eng: 'scoff, mock', kor: '비웃다, 조롱하다' },
  { eng: 'unruly', kor: '다루기 힘든, 제멋대로인' },
  { eng: 'scorn', kor: '경멸, 멸시' },
  { eng: 'hoot', kor: '폭소, 콧방귀' },
  { eng: 'stern', kor: '근엄한' },
  { eng: 'dismay', kor: '실망, 경악' },
  { eng: 'blemish', kor: '흠, 티, 오점' },
  { eng: 'misfit', kor: '부적응자' },
  { eng: 'grandiose', kor: '거창한' },
  { eng: 'commence', kor: '시작하다' },
  { eng: 'prominently', kor: '대문 짝만하게' },
  { eng: 'flap', kor: '날개를 퍼덕거리다' },
  { eng: 'breed', kor: '새끼를 낳다' },
  { eng: 'swamp', kor: '늪' },
  { eng: 'logging', kor: '벌목' },
  { eng: 'yam', kor: '참마' },
  { eng: 'revert', kor: '되돌아가다' },
  { eng: 'delicacy', kor: '여림, 섬세함' },
  { eng: 'virulent', kor: '악성의' },
  { eng: 'confine', kor: '국한시키다, 넣다' },
  { eng: 'notwithstanding', kor: '~에도 불구하고' },
  { eng: 'malnourished', kor: '영양실조의' },
  { eng: 'drench', kor: '흠뻑 적시다' },
  { eng: 'amber', kor: '호박, 호박색' },
  { eng: 'pragmatism', kor: '실용주의' },
  { eng: 'termite', kor: '흰개미' },
  { eng: 'proboscis', kor: '코, 주둥이' },
  { eng: 'chimney', kor: '굴뚝' },
  { eng: 'forthcoming', kor: '다가오는, 기꺼이 밝히는' },
  { eng: 'hangar', kor: '비행기 격납고' },
  { eng: 'foresee', kor: '예견하다' },
  { eng: 'bulk', kor: '대부분, 규모' },
  { eng: 'roughly', kor: '대략' },
  { eng: 'indigenous', kor: '원산의, 토종의' },
  { eng: 'emcompass', kor: '포함하다, 아우르다' },
  { eng: 'analogous', kor: '유사한' },
  { eng: 'intact', kor: '온전한' },
  { eng: 'archipelago', kor: '군도, 다도해' },
  { eng: 'migration', kor: '이주' },
  { eng: 'pigment', kor: '색소' },
  { eng: 'predominantly', kor: '대개, 대부분' },
  { eng: 'commodity', kor: '상품' },
  { eng: 'underwrite', kor: '동의하다' },
  { eng: 'bearer', kor: '운반인, 전달자' },
  { eng: 'alias, pseudonym', kor: '가명' },
  { eng: 'no string attached', kor: '아무 조건 없이' },
  { eng: 'pilgrims', kor: '순례자' },
  { eng: 'stampede', kor: '우르르 몰림' },
  { eng: 'move onward', kor: '전진하다' },
  { eng: 'perpetrator', kor: '가해자' },
  { eng: 'ulcer', kor: '궤양' },
  { eng: 'relentlessly', kor: '가차없이' },
  { eng: 'aristocrat', kor: '귀족' },
  { eng: 'swoop', kor: '급강하하다' },
  { eng: 'slither, glide, slide, skitter', kor: '스르르 나아가다' },
  { eng: 'expedition, exploration', kor: '탐험' },
  { eng: 'dementia', kor: '치매' },
  { eng: 'grove', kor: '과수원' },
  { eng: 'replenish', kor: '다시 채우다, 보충하다' },
  { eng: 'water table', kor: '수위' },
  { eng: 'divert', kor: '다른 쪽으로 돌리다' },
  { eng: 'desalination', kor: '염분제거, 담수화' },
  { eng: 'whereby', kor: '~하는' },
  { eng: 'discard', kor: '버리다' },
  { eng: 'abode', kor: '거주지, 집' },
  { eng: 'deflect', kor: '방향을 바꾸다' },
  { eng: 'officious', kor: '거들먹거리는, 위세부리는' },
  { eng: 'obfuscate', kor: '애매하게 만들다' },
  { eng: 'nebulous, vague', kor: '흐릿한, 모호한' },
  { eng: 'nefarious', kor: '범죄의' },
  { eng: 'morose', kor: '시무룩한' },
  { eng: 'mollify, placate', kor: '달래다' },
  { eng: 'allay', kor: '누그러뜨리다, 진정시키다' },
  { eng: 'assuage', kor: '달래다, 완화케하다' },
  { eng: 'ostensible', kor: '표면적으로는' },
  { eng: 'pedantic', kor: '현학적' },
  { eng: 'paucity', kor: '부족, 결핍' },
  { eng: 'plethora', kor: '과다, 과잉' },
  { eng: 'ballot', kor: '투표용지' },
  { eng: 'upbringing', kor: '양육' },
  { eng: 'levy', kor: '징수하다' },
  { eng: 'reinstate', kor: '원상태로 하다' },
  { eng: 'oversight', kor: '감독, 감시' },
  { eng: 'tally', kor: '새기다, 기록하다' },
  { eng: 'lessee', kor: '임차인' },
  { eng: 'capsize', kor: '뒤집다' },
  { eng: 'hype', kor: '속이다' },
  { eng: 'refurbishment', kor: '쇄신' },
  { eng: 'refurbish', kor: '개조, 새로 꾸미다' },
  { eng: 'overthrow', kor: '뒤엎다' },
  { eng: 'misery', kor: '불행' },
  { eng: 'fend', kor: '받아넘기다' },
  { eng: 'pier', kor: '부두, 방파제' },
  { eng: 'presumptous', kor: '주제넘은' },
  { eng: 'suburban', kor: '교외에 사는' },
  { eng: 'conceit', kor: '자만, 자부심' },
  { eng: 'shortcut', kor: '지름길' },
  { eng: 'sympathize', kor: '동정하다, 동감하다' },
  { eng: 'obstinate', kor: '완고한' },
  { eng: 'confiscate', kor: '압수하다' },
  { eng: 'flourish', kor: '번창하다' },
  { eng: 'bustle', kor: '바삐 움직이다' },
  { eng: 'stride', kor: '성큼성큼 걷다' },
  { eng: 'fateful', kor: '운명적인, 치명적인' },
  { eng: 'backlog', kor: '밀린 일, 잔고' },
  { eng: 'pluck', kor: '뽑다, 잡아당기다' },
  { eng: 'utilization', kor: '이용, 활용' },
  { eng: 'loophole', kor: '허점, 구멍' },
  { eng: 'embargo', kor: '금수 조치' },
  { eng: 'infringe', kor: '어기다, 침해하다' },
  { eng: 'reiterate', kor: '되풀이하다' },
  { eng: 'revive', kor: '활기를 되찾다, 부활시키다' },
  { eng: 'deputy', kor: '대리인' },
  { eng: 'proxy', kor: '대리권' },
  { eng: 'envoy', kor: '사절, 특사' },
  { eng: 'whirl', kor: '빙글빙글 돌리다' },
  { eng: 'verdict', kor: '판결' },
  { eng: 'snag', kor: '문제, 걸리다, 잡아채다' },
  { eng: 'batch', kor: '한 회분, 일괄' },
  { eng: 'rim', kor: '가장테리, 테' },
  { eng: 'coherent', kor: '일관성 있는' },
  { eng: 'conceive', kor: '상상하다' },
  { eng: 'acumen', kor: '감각' },
  { eng: 'adroit', kor: '노련한' },
  { eng: 'dexterity', kor: '재주' },
  { eng: 'adamant', kor: '요지부동의, 단호한' },
  { eng: 'ambidexterous', kor: '양손잡이의' },
  { eng: 'augment', kor: '늘리다, 증가시키다' },
  { eng: 'watchword', kor: '좌우명, 표어' },
  { eng: 'elucidate', kor: '자세히 설명하다' },
  { eng: 'entice', kor: '유도하다, 유인하다' },
  { eng: 'archaic', kor: '낡은, 구식, 고대의' },
  { eng: 'arcane', kor: '신비로운, 불가사의한' },
  { eng: 'apocryphal', kor: '출처가 불분명한' },
  { eng: 'antithesis', kor: '반대되는 것, 대조' },
  { eng: 'animosity', kor: '반감, 적대감' },
  { eng: 'apathy', kor: '무관심' },
  { eng: 'enmity', kor: '원한, 증오, 적대감' },
  { eng: 'bureau', kor: '사무국' },
  { eng: 'jeopardous', kor: '위험한' },
  { eng: 'trainee', kor: '교육을 받는 사람' },
  { eng: 'remedy', kor: '처리하다, 해결, 치료' },
  { eng: 'chop', kor: '끊다' },
  { eng: 'destined', kor: '예정된' },
  { eng: 'devise', kor: '창안하다' },
  { eng: 'suite', kor: '묶음' },
  { eng: 'temporal', kor: '속세의' },
  { eng: 'linger', kor: '더 오래 머물다' },
  { eng: 'allegedly', kor: '주장한 바에 의하면' },
  { eng: 'constrain', kor: '~하게 만들다, 제한하다' },
  { eng: 'constrainedly', kor: '억지로' },
  { eng: 'scrutiny', kor: '정밀한 조사' },
  { eng: 'instrumental', kor: '중요한' },
  { eng: 'induction', kor: '귀납법' },
  { eng: 'juvenile', kor: '청소년의' },
  { eng: 'embark', kor: '탑승하다' },
  { eng: 'booklet', kor: '책자' },
  { eng: 'timely', kor: '시기적절한' },
  { eng: 'thoughtful', kor: '배려심 있는' },
  { eng: 'lawmaker', kor: '입법자' },
  { eng: 'bilateral', kor: '쌍방의' },
  { eng: 'accountable', kor: '책임이 있는' },
  { eng: 'optional', kor: '임의의' },
  { eng: 'stationary', kor: '정지된' },
  { eng: 'brew', kor: '양조하다' },
  { eng: 'profitability', kor: '수익성' },
  { eng: 'consolidation', kor: '통합' },
  { eng: 'contingency', kor: '우발성, 만일의 사태' },
  { eng: 'curb', kor: '억제하다' },
  { eng: 'imagery', kor: '이미지, 사진' },
  { eng: 'transit', kor: '통과, 수송, 교통' },
  { eng: 'responsive', kor: '민감한' },
  { eng: 'potent', kor: '유력한' },
  { eng: 'voucher', kor: '할인권' },
  { eng: 'newsletter', kor: '소식지' },
  { eng: 'standpoint', kor: '관점' },
  { eng: 'courier', kor: '배달원' },
  { eng: 'escalate', kor: '확대되다' },
  { eng: 'adjoin', kor: '인접하다' },
  { eng: 'shortcoming', kor: '결점, 단점' },
  { eng: 'advisable', kor: '현명한' },
  { eng: 'withstand', kor: '참다' },
  { eng: 'vicinity', kor: '부근' },
  { eng: 'incidental, collateral', kor: '부수적인' },
  { eng: 'salute', kor: '경례를 하다' },
  { eng: 'chore', kor: '일' },
  { eng: 'waiver', kor: '포기' },
  { eng: 'patronage', kor: '후원' },
  { eng: 'streamline', kor: '능률화하다, 유선형, 간소화하다' },
  { eng: 'attic', kor: '다락방' },
  { eng: 'gadget', kor: '도구' },
  { eng: 'scrutinize', kor: '세심히 조사하다' },
  { eng: 'provisional', kor: '임시의' },
  { eng: 'prosper', kor: '번영하다' },
  { eng: 'endowment', kor: '기증' },
  { eng: 'agreeable', kor: '쾌활한' },
  { eng: 'flux', kor: '유동' },
  { eng: 'rebate', kor: '환불' },
  { eng: 'candidacy', kor: '입후보' },
  { eng: 'jeopardize', kor: '위험에 처하다' },
  { eng: 'deregulation', kor: '자유화' },
  { eng: 'arbitration', kor: '중재' },
  { eng: 'apparel', kor: '의류' },
  { eng: 'lavatory', kor: '화장실' },
  { eng: 'paycheck', kor: '급료' },
  { eng: 'postage', kor: '배송료' },
  { eng: 'sensational', kor: '선량한' },
  { eng: 'allot', kor: '차별하다' },
  { eng: 'eloquent', kor: '유창한' },
  { eng: 'sluggish', kor: '부진한' },
  { eng: 'claimant', kor: '청구인' },
  { eng: 'stella', kor: '별의, 뛰어난' },
  { eng: 'strenuous', kor: '격렬한' },
  { eng: 'ingenuity', kor: '기발한 재주' },
  { eng: 'detour', kor: '우회로' },
  { eng: 'outperform', kor: '능가하다' },
  { eng: 'erroneous', kor: '잘못된' },
  { eng: 'attire', kor: '복장' },
  { eng: 'emphatically', kor: '강조하여' },
  { eng: 'surcharge', kor: '추가요금' },
  { eng: 'appreciate', kor: '진가를 알아보다' },
  { eng: 'stuffy', kor: '답답한' },
  { eng: 'timeline', kor: '시간표' },
  { eng: 'fondly', kor: '애정을 담아' },
  { eng: 'fondness', kor: '좋아함' },
  { eng: 'utensil', kor: '기구, 도구' },
  { eng: 'eloquence', kor: '웅변하는' },
  { eng: 'inducement', kor: '유인' },
  { eng: 'depository', kor: '보관소' },
  { eng: 'collate', kor: '수집하다' },
  { eng: 'effortless', kor: '편한' },
  { eng: 'induct', kor: '취임시키다' },
  { eng: 'collateralize', kor: '담보 물건으로 보증하다' },
  { eng: 'florist', kor: '꽃집' },
  { eng: 'petitioner', kor: '탄원자' },
  { eng: 'tirelessly', kor: '끊임없이' },
  { eng: 'perishable', kor: '잘 상하는' },
  { eng: 'attentively', kor: '조심스럽게' },
  { eng: 'officiate', kor: '공무를 수행하다' },
  { eng: 'expressway', kor: '고속도로' },
  { eng: 'condominium', kor: '아파트' },
  { eng: 'strenuously', kor: '활기차게' },
  { eng: 'concierge', kor: '안내원' },
  { eng: 'broil', kor: '굽다' },
  { eng: 'cordially', kor: '다정한' },
  { eng: 'agreeably', kor: '기분 좋게' },
  { eng: 'enrollee', kor: '등록자' },
  { eng: 'overpass', kor: '고가도로' },
  { eng: 'vacantly', kor: '멍하니' },
  { eng: 'terminable', kor: '유한한' },
  { eng: 'volatile', kor: '변덕스러운, 불안한, 휘발성의' },
  { eng: 'outpace', kor: '앞지르다' },
  { eng: 'aggregate', kor: '합계, 총액' },
  { eng: 'binge', kor: '폭식하다' },
  { eng: 'mainland', kor: '본토' },
  { eng: 'miscarriage', kor: '유산' },
  { eng: 'affiliate', kor: '제휴하다' },
  { eng: 'deceased', kor: '사망한, 고인' },
  { eng: 'outrage', kor: '격분, 분노' },
  { eng: 'flagship', kor: '주력, 서비스' },
  { eng: 'pop-up', kor: '임시 매장의' },
  { eng: 'savvy', kor: '상식 있는, 요령있는' },
  { eng: 'posh', kor: '화려한, 상류층' },
  { eng: 'top-tier', kor: '일류의' },
  { eng: 'culpability', kor: '책임' },
  { eng: 'behemoth', kor: '거대기업' },
  { eng: 'backlash', kor: '반발' },
  { eng: 'come under fire', kor: '비난을 받다' },
  { eng: 'grapple with', kor: '~을 해결하려고 노력하다' },
  { eng: 'stumbling block', kor: '장애물' },
  { eng: 'juggernaut', kor: '비대한 조직' },
  { eng: 'win heart', kor: '마음을 얻다' },
  { eng: 'slam', kor: '맹비난하다' },
  { eng: 'resilient', kor: '회복력있는' },
  { eng: 'call for', kor: '요구하다' },
  { eng: 'mayhem', kor: '대혼란' },
  { eng: 'grave', kor: '심각한' },
  { eng: 'benchmark', kor: '기준점' },
  { eng: 'hitch', kor: '문제, 장애' },
  { eng: 'protracted', kor: '오래 계속된' },
  { eng: 'obnoxious', kor: '아주 불쾌한' },
  { eng: 'indignant', kor: '분개한' },
  { eng: 'lay claim to', kor: '~에 대한 권리를 주장하다' },
  { eng: 'islet', kor: '작은 섬' },
  { eng: 'commendatory', kor: '칭찬하는, 추천의' },
  { eng: 'commiserative', kor: '동정심있는, 인정 많은' },
  { eng: 'antagonistic', kor: '적대적인' },
  { eng: 'provocation', kor: '도발, 자극' },
  { eng: 'squdron', kor: '비행중대, 소함대' },
  { eng: 'bank on', kor: '~에 의존하다' },
  { eng: 'drill', kor: '훈련' },
  { eng: 'flurry', kor: '소동' },
  { eng: 'languish', kor: '약화되다' },
  { eng: 'envisage', kor: '예상하다' },
  { eng: 'bristle at', kor: '~에 발끈하다' },
  { eng: 'concur', kor: '동의하다' },
  { eng: 'irrespective of', kor: '~에 상관없이' },
  { eng: 'misgivings', kor: '의혹, 불안감' },
  { eng: 'stoke', kor: '더 부추기다' },
  { eng: 'acquisition deal', kor: '인수 계약' },
  { eng: 'foothold', kor: '발 디딜 곳, 발판' },
  { eng: "throw one's hat in the ring", kor: '재도전하다, 출사표를 던지다' },
  { eng: 'shed tears', kor: '눈물을 흘리다' },
  { eng: 'mosmerize', kor: '마음을 사로잡다' },
  { eng: 'garner', kor: '얻다, 모으다' },
  { eng: 'ditch', kor: '버리다' },
  { eng: 'debt-ridden', kor: '적자에 허덕이는' },
  { eng: 'crunch', kor: '부족사태' },
  { eng: 'stay afloat', kor: '빚지지 않고 있다' },
  { eng: 'all-out', kor: '총력을 기울인, 전면적인' },
  { eng: 'bridge the gap', kor: '공백을 메우다' },
  { eng: 'pathogens', kor: '병원체' },
  { eng: 'inoculation', kor: '접종' },
  { eng: 'unveil', kor: '발표하다' },
  { eng: 'pageant', kor: '미인 대회' },
  { eng: 'runner-up', kor: '2위' },
  { eng: 'accomplished', kor: '기량이 뛰어난' },
  { eng: 'gordian knot', kor: '아주 힘든 문제' },
  { eng: 'atrocity', kor: '(전시 외)잔혹행위' },
  { eng: 'thwart', kor: '(계획 등)좌절시키다' },
  { eng: 'sour', kor: '시다, 안 좋아지다, 틀어지다' },
  { eng: 'intimidated', kor: '겁을 내는' },
  { eng: 'voyeurism', kor: '관음증' },
  { eng: 'ebullience', kor: '열광' },
  { eng: 'concession', kor: '양보, 양해' },
  { eng: 'stem', kor: '막다, 저지하다' },
  { eng: 'disgruntle', kor: '기분 상하게 하다' },
  { eng: 'sickle', kor: '낫' },
  { eng: 'file', kor: '(소송을)제기하다' },
  { eng: 'chauffer', kor: '고급 운전 기사' },
  { eng: 'bracket', kor: '계층' },
  { eng: 'sentence', kor: '(형을)선고하다' },
  { eng: 'fledgling', kor: '초보, 신출내기' },
  { eng: 'catch A off guard', kor: 'A의 허를 찌르다' },
  { eng: 'revolve around', kor: '~을 중심으로 다루다' },
  { eng: 'defamation', kor: '중상, 명예훼손' },
  { eng: 'at odds with', kor: '갈등을 빚고 있다' },
  { eng: 'wrangling', kor: '분쟁' },
  { eng: 'up in arms', kor: '~에 반기를 들어' },
  { eng: 'repeal', kor: '폐지하다' },
  { eng: 'bear the brunt of', kor: '~을 정면에서 맞다' },
  { eng: 'geopolitical', kor: '지정학의' },
  { eng: 'woe', kor: '고민, 문제' },
  { eng: 'blinch', kor: '덜덜 떨면서 두려워하다' },
  { eng: 'flinch', kor: '움찔하다' },
  { eng: 'clinch', kor: '성사시키다, 부둥켜안음' },
  { eng: 'nab', kor: '가져가다' },
  { eng: "raise one's guard", kor: '~를 주의 깊게 준비할 것을' },
  { eng: 'outbound', kor: '떠나는' },
  { eng: 'log', kor: '기록하다' },
  { eng: 'remuneration', kor: '보수' },
  { eng: 'sideline', kor: '출전을 못하게 하다, 열외로 취급하다' },
  { eng: 'veer', kor: '방향을 바꾸다' },
  { eng: 'pound', kor: '치다, 두드리다' },
  { eng: 'weir', kor: '둑' },
  { eng: 'displace', kor: '쫓아내다' },
  { eng: 'confutation', kor: '논박, 반증' },
  { eng: 'encapsulation', kor: '함축' },
  { eng: 'liken A to B', kor: 'A를 B에 비유하다' },
  { eng: 'quintet', kor: '5인조' },
  { eng: 'strike a chord with', kor: '~의 심금을 울리다' },
  { eng: 'woo', kor: '지지를 호소하다, 구애하다' },
  { eng: 'extortionist', kor: '강탈자, 착취자' },
  { eng: 'unilaterally', kor: '일방적으로' },
  { eng: 'private equity', kor: '사모펀드' },
  { eng: 'repurcussion', kor: '영향' },
  { eng: 'uncontested', kor: '반대가 없는' },
  { eng: 'turn A down', kor: 'A를 거절하다' },
  { eng: 'germinate', kor: '싹트다' },
  { eng: 'put on hold', kor: '~을 보류하다' },
  { eng: 'off-limit', kor: '출입금지의' },
  { eng: 'graviate', kor: '인력에 끌리다' },
  { eng: 'pursuit', kor: '일, 활동' },
  { eng: 'frolic', kor: '즐겁게 뛰놀다' },
  { eng: 'scorching', kor: '모든 걸 태워버릴듯이 더운' },
  { eng: 'worn out', kor: '닳아서 못 쓰게된' },
  { eng: 'phenomenal', kor: '경이적인' },
  { eng: 'against the backdrop (of)', kor: '~을 배경으로' },
  { eng: 'pundit', kor: '전문가, 권위자' },
  { eng: 'retaliation', kor: '보복' },
  { eng: 'find solace in', kor: '~에서 위안을 얻다' },
  { eng: 'portmanteau', kor: '혼성어' },
  { eng: 'go viral', kor: '입소문이 나다' },
  { eng: 'pick at', kor: '깨작거리다' },
  { eng: 'take issue with', kor: '문제삼다, 트집잡다' },
  { eng: 'trust into limelight', kor: '주목을 받다' },
  { eng: 'confectionery', kor: '과자류, 단 음식' },
  { eng: 'a slew of', kor: '많은' },
  { eng: 'A-lister', kor: '일류의' },
  { eng: 'a bunch of', kor: '다수의' },
  { eng: 'quartet', kor: '4인조' },
  { eng: 'bigwig', kor: '주요인물' },
  { eng: 'high-profile', kor: '세간의 이목을 끄는' },
  { eng: 'demograpic', kor: '인구통계의' },
  { eng: 'timeliness', kor: '적시, 시기적절함' },
  { eng: 'grasp', kor: '완전히 이해하다, 파악하다' },
  { eng: 'double down on', kor: '~에 대한 노력을 배가하다' },
  { eng: 'phase-out', kor: '단계적 철수' },
  { eng: 'pay heed to', kor: '~에 주의하다' },
  { eng: 'quota', kor: '한도, 몫' },
  { eng: 'be accustomed to', kor: '~에 익숙하다' },
  { eng: 'makeshift', kor: '임시변통의' },
  { eng: 'nosedive', kor: '급락하다' },
  { eng: 'kick off', kor: '시작되다' },
  { eng: 'transpire', kor: '일어나다' },
  { eng: 'operating profit', kor: '영업이익' },
  { eng: 'sovereignty', kor: '통치권' },
  { eng: 'hamper', kor: '방해하다' },
  { eng: 'uphold', kor: '유지시키다' },
  { eng: 'promenade', kor: '산책로' },
  { eng: 'onlooker', kor: '구경꾼' },
  { eng: 'vaulted', kor: '아치형의' },
  { eng: 'upbeat', kor: '낙관적인' },
  { eng: 'tacky', kor: '엉성한' },
  { eng: 'boisterously', kor: '떠들석하게' },
  { eng: 'poignant', kor: '가슴 아픈' },
  { eng: 'troupe', kor: '공연단' },
  { eng: 'projectile', kor: '발사체' },
  { eng: 'lift-off', kor: '이륙하다' },
  { eng: 'go off', kor: '발사되다' },
  { eng: 'much-anticipated', kor: '기대를 모은' },
  { eng: 'mogul', kor: '거물, 실력자' },
  { eng: 'procure', kor: '구하다, 입수하다' },
  { eng: 'suitor', kor: '타 기업 인수를 원하는 기업' },
  { eng: 'stir up', kor: '일으키다' },
  { eng: 'turn a blind eye to', kor: '~을 못 본체하다' },
  { eng: 'take flak', kor: '격렬한 비난을 감수하다' },
  { eng: 'step up', kor: '~을 강화하다' },
  { eng: 'cohabit', kor: '동거하다' },
  { eng: 'talk something out', kor: '~을 철저히 논하다' },
  { eng: 'unwed', kor: '미혼의' },
  { eng: 'maternity leave', kor: '육아휴직' },
  { eng: 'get into full swing', kor: '최고조에 달하다' },
  { eng: 'carve out', kor: '~을 개척하다' },
  { eng: 'stake', kor: '지분, 말뚝, 화형대' },
  { eng: 'catchphrase', kor: '유명하다, 선전구호' },
  { eng: 'moribund', kor: '빈사상태의, 소멸직전의' },
  { eng: 'go up in smoke', kor: '수포로 돌아가다' },
  { eng: 'tie the knot', kor: '결혼을 하다' },
  { eng: 'iconic', kor: '우상의' },
  { eng: 'stigma', kor: '오명' },
  { eng: 'constitutionality', kor: '합헌성' },
  { eng: 'hearing', kor: '공판, 심리' },
  { eng: 'memorial service', kor: '추도식' },
  { eng: 'subsidiary', kor: '자회사' },
  { eng: 'asphyxiation', kor: '질식' },
  { eng: 'inaugural', kor: '취임식의' },
  { eng: 'outlier', kor: '본체를 떠난 물건' },
  { eng: 'hail from', kor: '~의 출신이다' },
  { eng: 'outing', kor: '여행, 견학' },
  { eng: 'in the aftermath of', kor: '~의 여파로' },
  { eng: 'wield', kor: '행사하다, 휘두르다' },
  { eng: 'doldrums', kor: '침울, 우울' },
  { eng: 'heighten', kor: '고조시키다' },
  { eng: 'coin', kor: '만들다, 주조하다' },
  { eng: 'contain', kor: '~이 들어있다, 억누르다, 방지하다' },
  { eng: 'excruciating', kor: '몹시 고통스러운' },
  { eng: 'point to', kor: '(이유로)~을 들먹이다' },
  { eng: 'as of', kor: '(날짜)일자로' },
  { eng: 'recurrence', kor: '시작하다' },
  { eng: 'topple', kor: '넘어지다' },
  { eng: 'the bereaved', kor: '사별을 당한 사람, 유족' },
  { eng: 'condolence', kor: '애도, 조의' },
  { eng: 'titillate', kor: '(성적으로)자극하다' },
  { eng: 'titivate', kor: '(외모를)가다듬다' },
  { eng: 'be behind the wheel', kor: '운전을 하다' },
  { eng: 'reinvent', kor: '다른 모습을 보여주다' },
  { eng: 'articulate', kor: '명료화하다, 분명히 표현하다' },
  { eng: 'deliverable', kor: '상품' },
  { eng: 'a meteoric rise to fame', kor: '일약 유명해짐' },
  { eng: 'seasonality', kor: '계절적 변동' },
  { eng: 'sweeping', kor: '전면적인' },
  { eng: 'have a short fuse', kor: '성미가 급하다' },
  { eng: 'split up', kor: '헤어지다' },
  { eng: 'dodge', kor: '기피하다, 재빨리 움직이다' },
  { eng: 'disenchanted', kor: '환멸을 느낀' },
  { eng: 'disoriented', kor: '(방향 감각 상실한)혼란' },
  { eng: 'preside over', kor: '~의 사회를 보다' },
  { eng: 'to no avail', kor: '헛되이' },
  { eng: 'caliber', kor: '구경, 직경, 재능' },
  { eng: 'perpetual bond', kor: '무기한 채권' },
  { eng: 'turmoil', kor: '혼란, 소란' },
  { eng: 'prostitute', kor: '매춘부' },
  { eng: 'wrongdoer', kor: '부정행위자, 범법자' },
  { eng: 'trajectory', kor: '궤적, 궤도' },
  { eng: 'liability', kor: '부채' },
  { eng: 'debacle', kor: '대실패' },
  { eng: 'lieutenant', kor: '중위' },
  { eng: 'reciprocate', kor: '화답하다' },
  { eng: 'conciliatory', kor: '논쟁을 초래할 듯한' },
  { eng: 'coercive', kor: '강압적인' },
  { eng: 'prod', kor: '재촉하다, 촉구하다' },
  { eng: 'under the radar', kor: '암암리에' },
  { eng: 'crackdown', kor: '엄중 단속' },
  { eng: 'albeit', kor: '비록 ~일지라도' },
  { eng: 'shady', kor: '수상한 구석이 있는' },
  { eng: 'bleak', kor: '암울한' },
  { eng: 'stave off', kor: '피하다, 간신히 모면하다' },
  { eng: 'offer sympathy', kor: '애도의 뜻을 표하다' },
  { eng: 'square one', kor: '출발점, 시작' },
  { eng: 'sullen', kor: '뚱한, 시무룩한' },
  { eng: 'bode well[ill] for[to]', kor: '…에게 길조[흉조]이다' },
  { eng: 'trade deficit', kor: '무역 적자' },
  { eng: 'outlook', kor: '전망' },
  { eng: 'dwindle', kor: '줄어들다' },
  { eng: 'murky', kor: '어두컴컴한, 흐린' },
  { eng: 'edge out', kor: '~을 서서히 몰아내다' },
  { eng: 'hand over', kor: '양도하다' },
  { eng: 'reignite', kor: '재점화하다' },
  { eng: 'capitalize on', kor: '~을 활용하다' },
  { eng: 'substance abuse', kor: '약물 남용' },
  { eng: 'long shot', kor: '거의 승산 없는 것' },
  { eng: 'snuff out', kor: '~을 완전히 끝내다' },
  { eng: 'no later than March next year', kor: '늦어도 내년 3월까지는' },
  { eng: 'plenary session', kor: '전체 회의, 총회' },
  { eng: 'brace for', kor: '~에 대비하다' },
  { eng: 'pittance', kor: '얼마 안 되는 돈' },
  { eng: 'relatable', kor: '공감대를 형성하는' },
  { eng: 'seek refuge with', kor: '~에게로 피신해가다' },
  { eng: 'exemplary', kor: '모범적인, 가혹한' },
  { eng: 'retaliate', kor: '보복하다' },
  { eng: 'juxtapose', kor: '병치하다[나란히 놓다]' },
  { eng: 'nullify', kor: '무효화하다' },
  { eng: 'amend', kor: '(법 등을) 개정하다' },
  { eng: 'descent', kor: '혈통, 가문, 가계' },
  { eng: 'milestone', kor: '중요한 단계' },
  { eng: 'ecstatic', kor: '황홀해 하는' },
  { eng: 'strain', kor: '부담, 혹사하다, 무리를 주다' },
  { eng: 'reminiscent', kor: '연상시키는' },
  { eng: 'detente', kor: '긴장 완화' },
  { eng: 'dampen', kor: '적시다, 꺾다' },
  { eng: 'setback', kor: '차질' },
  { eng: 'threshold', kor: '문지방, 문턱' },
  { eng: 'bout', kor: '한바탕, 한차례' },
  { eng: 'admonish', kor: '꾸짖다, 책망하다' },
  { eng: 'adumbrate', kor: '간략하게 알리다' },
  { eng: 'accrete', kor: '함께 커지다, 공생하다, 부착하다' },
  { eng: 'restitution', kor: '반환'},
  { eng: 'inscrutable', kor: '불가해한, 헤아리기 어려운'},
  { eng: 'effusive', kor: '야단스러운, 과장된'},
  { eng: 'fulsome', kor: '지나친'},
  { eng: 'foment', kor: '조성, 조장하다'},
  { eng: 'fetter', kor: '구속하다, 족쇄를 채우다'},
  { eng: 'veritable', kor: '진정한'},
  { eng: 'dispense', kor: '제공하다, 조제하다'},
  { eng: 'discern', kor: '알아차리다, 파악하다'},
  { eng: 'indispensable', kor: '필수적인'},
  { eng: 'finesse', kor: '수완, 재간, 교묘하게 처리하다'},
  { eng: 'opaque', kor: '불투명한'},
  { eng: 'lucid', kor: '명쾌한, 명료한'},
  { eng: 'limpid, pellucid', kor: '맑은, 투명한'},
  { eng: 'pejorative, derogatory', kor: '경멸적인, 비판적인'},
  { eng: 'peccadillo', kor: '사소한 실수'},
  { eng: 'peripatetic', kor: '이동해 다니는, 순회하는'},
  { eng: 'perennial', kor: '지속되는, 계속 반복되는'},
  { eng: 'preposterous', kor: '말도 안 되는, 터무니 없는'},
  { eng: 'exorbitant', kor: '과도한, 지나친'},
  { eng: 'transquil', kor: '고요한, 평온한'},
  { eng: 'repulsive', kor: '역겨운, 혐오스러운'},
  { eng: 'rudimentary', kor: '가장 기초적인, 제대로 발달하지 못한'},
  { eng: 'contingent', kor: '대표단, 선발대'},
  { eng: 'negligible', kor: '무시해도 될 정도의'},
  { eng: 'mediocrity', kor: '보통, 평범'},
  { eng: 'mediocre', kor: '보통 밖에 안 되는'},
  { eng: 'philanthropy', kor: '독지, 자선활동'},
  { eng: 'insistent', kor: '고집하는, 주장하는, 계속되는'},
  { eng: 'meager', kor: '메마른'},
  { eng: 'lethargy', kor: '무기력'},
  { eng: 'agitate', kor: '주장하다, 요구하다'},
  { eng: 'agitation', kor: '불안, 동요'},
  { eng: 'vagary', kor: '엉뚱한 생각, 변덕'},
  { eng: 'whim', kor: '기분, 변덕'},
  { eng: 'whimsical', kor: '엉뚱한, 기발한'},
  { eng: 'mercurial', kor: '변덕스러운(마음이 오르락 내리락하는), 수은이 함유된'},
  { eng: 'mendacious', kor: '진실을 말하지 않는, 허위의'},
  { eng: 'mendacity', kor: '거짓된 행동'},
  { eng: 'maverick', kor: '개성이 강한 사람, 독립적인 사람'},
  { eng: 'mawkish', kor: '감상적인'},
  { eng: 'maudlin', kor: '감성적인, 넋두리하는'},
  { eng: 'lugubrious, doleful', kor: '침울한'},
  { eng: 'mellifluous', kor: '달콤한, 감미로운'},
  { eng: 'mendicant', kor: '거지, 탁발 수도사'},
  { eng: 'malleable', kor: '펴서 늘릴 수 있는, 잘 변하는, 가단성 있는'},
  { eng: 'malinger', kor: '꾀병을 부리다'},
  { eng: 'indeliable', kor: '잊을 수가 없는, 지워지지 않는'},
  { eng: 'clairvoyant', kor: '신통력, 예지력'},
  { eng: 'clairvoyant dream', kor: '예지몽'},
  { eng: 'ricochet', kor: '(어떤 것에 맞고)튀어 나온'},
  { eng: 'conjugal, matrimonial', kor: '부부의, 부부관계의'},
  { eng: 'saunter', kor: '한가롭게 걷다'},
  { eng: 'pelt', kor: '공격하다, 퍼붓다, (동물의)생가죽'},
  { eng: 'vacillate, waver', kor: '흔들리다, 자주 바뀌다, 결정을 못하다'},
  { eng: 'usurp', kor: '빼앗다, 찬탈하다'},
  { eng: 'unctuous', kor: '(말, 행동이)번지르르한'},
  { eng: 'venal', kor: '부패한'},
  { eng: 'venial', kor: '용서할 수 있는, 가벼운'},
  { eng: 'venial sin', kor: '경죄'},
  { eng: 'untoward', kor: '뜻밖의, 불행한, 난처한'},
  { eng: 'unwieldy', kor: '다루기 불편한, 거추장스러운'},
  { eng: 'potable', kor: '음료로 적합한, 마실 수 있는'},
  { eng: 'potent', kor: '강한'},
  { eng: 'rancid', kor: '산패한, 부패한, 상한'},
  { eng: 'vitiate', kor: '(효과를)해치다, 망치다'},
  { eng: 'uncouth', kor: '무례한, 상스러운'},
  { eng: 'benighted', kor: '무지몽매한, 미개한'},
  { eng: 'decorous', kor: '점잖은, 예의 바른'},
  { eng: 'dearth', kor: '부족, 결핍'},
  { eng: 'culpable', kor: '과실이 있는'},
  { eng: 'culprit', kor: '범인, 장본인'},
  { eng: 'clandestine', kor: '비밀리에 하는, 은밀한'},
  { eng: 'commodious', kor: '널찍한'},
  { eng: 'remiss', kor: '태만한'},
  { eng: 'repudiate', kor: '거부하다, 부인하다'},
  { eng: 'recalcitrant', kor: '저항하는, 반항하는'},
  { eng: 'querulous', kor: '불평하는, 짜증내는'},
  { eng: 'pusillanimous', kor: '겁 많은, 소심한'},
  { eng: 'puerile', kor: '유치한, 바보같은'},
  { eng: 'petulance', kor: '심술'},
  { eng: 'pulverize', kor: '분쇄하다, 가루로 만들다'},
  { eng: 'preponderate', kor: '다른 것보다 무게가 더 나가다'},
  { eng: 'reverberate', kor: '울리다, 파문을 불러 일으키다'},
  { eng: 'elate', kor: '고무하다, 우쭐대게 하다, 앙양시키다'},
  { eng: 'engross', kor: '몰두하게 하다, 매점하다'},
  { eng: 'massacre', kor: '대학살, 대패시키다'},
  { eng: 'puny', kor: '작고 연약한'},
  { eng: 'colossal', kor: '거대한, 엄청난'},
  { eng: 'profane', kor: '신성모독적인, 불경한'},
  { eng: 'propitiate, placate', kor: '달래다'},
  { eng: 'prolix', kor: '장황한'},
  { eng: 'probity', kor: '정직성'},
  { eng: 'prevarigate', kor: '둘러대다, 얼버무리다'},
  { eng: 'quibble', kor: '옥신각신하다, 불만'},
  { eng: 'pristine', kor: '완전 새 것 같은, 아주 깨끗한'},
  { eng: 'obstuse', kor: '둔한, 둔감한'},
  { eng: 'obviate', kor: '제거하다'},
  { eng: 'obsequious, servile', kor: '아부하는, 굽실거리는'},
  { eng: 'oblique', kor: '완곡한, 에두른, 간접적인'},
  { eng: 'obstreperous', kor: '정신없이 날뛰는'},
  { eng: 'intransigent', kor: '고집스러운, 비협조적인'},
  { eng: 'intractable', kor: '다루기 힘든'},
  { eng: 'invective', kor: '욕설'},
  { eng: 'polemic', kor: '격론, 격렬한 비판'},
  { eng: 'portentous', kor: '(불길한)전조가 되는, 거들먹거리는'},
  { eng: 'pompous', kor: '젠체하는, 거만한'},
  { eng: 'precursor', kor: '선도자'},
  { eng: 'portend, omen', kor: '(불길한)전조, 징후'},
  { eng: 'predilection', kor: '선호, 매우 좋아함'},
  { eng: 'precocious', kor: '조숙한, 아이 같지 않은'},
  { eng: 'dilatory', kor: '미적거리는, 지체시키는'},
  { eng: 'ebullience', kor: '(감정의)격발'},
  { eng: 'ebullient', kor: '패기만만한, 사기가 충천한'},
  { eng: 'expunge', kor: '(정보, 기억을)삭제하다'},
  { eng: 'incongruent', kor: '일치하지 않는, 조화롭지 않은'},
  { eng: 'tribunal', kor: '재판소, 법원'},
  { eng: 'relegate', kor: '격하시키다, 강등시키다'},
  { eng: 'recant', kor: '철회하다'},
  { eng: 'rescind, repeal', kor: '폐지하다'},
  { eng: 'replete', kor: '~이 가득한, 포식을 한'},
  { eng: 'respite', kor: '일시적 중단, 유예'},
  { eng: 'reprieve', kor: '형 집행을 취소하다'},
  { eng: 'vestige', kor: '자취, 흔적'},
  { eng: 'repose', kor: '안식하다, 휴식, 수면'},
  { eng: 'reprisal, retaliation', kor: '보복, 앙갚음'},
  { eng: 'remonstarate', kor: '항의하다, 불평하다'},
  { eng: 'resplendent', kor: '눈부신, 찬란하다'},
  { eng: 'even out', kor: '잠잠해지다'},
  { eng: 'crop up', kor: '불쑥 나타나다, 발생하다'},
  { eng: 'improvise', kor: '즉흥적으로 하다'},
  { eng: 'reprehensible, deplorable', kor: '부끄러운, 비난받을 만한, 개탄스러운'}

]

let currentQuestionIndex = 0; //문제 번호
let score = 0;
let questionLanguage; //영어 or 한글
let wrongWords = []; // 틀린 단어들을 저장할 배열 추가
let attemptedQuestions = 0; // 시도한 문제 수

///////
// '단어 찾아보기' 버튼 클릭 이벤트 리스너
searchWordBtn.addEventListener('click', function() {
  const inputWord = searchWordInput.value.trim(); // 앞뒤 공백 제거
  const foundWord = wordList.find(word => word.eng.toLowerCase() === inputWord.toLowerCase());

  // 말풍선 컨테이너를 생성하고 스타일을 적용
  const container = document.createElement('div');
  container.className = 'speech-bubble';
  
  const content = document.createElement('div');
  content.className = 'speech-bubble-content';

  if (foundWord) {
      // 단어가 존재하는 경우
      const wordElement = document.createElement('span');
      wordElement.className = 'speech-bubble-highlight';
      wordElement.textContent = foundWord.eng;
      
      const meaningElement = document.createElement('p');
      meaningElement.textContent = `뜻: ${foundWord.kor}`;
      
      content.appendChild(wordElement);
      content.appendChild(meaningElement);
  } else {
      // 단어가 존재하지 않는 경우
      content.textContent = "리스트에 없는 단어입니다.";
      content.classList.add('error-message');
      // 또는 더 간단히
      // content.style.color = '#ef4444';
  }

  container.appendChild(content);
  
  // 기존 결과를 지우고 새로운 말풍선을 추가
  searchWordResult.innerHTML = '';
  searchWordResult.appendChild(container);
  
  // 입력 필드 초기화
  searchWordInput.value = '';
});
//////
//영어 단어 시험
startEngQuizBtn.addEventListener('click', () => {
  questionLanguage = 'eng';
  quizContainer.style.display = 'block';
  initQuiz();
});

//한글 단어 시험
startKorQuizBtn.addEventListener('click', () => {
  questionLanguage = 'kor';
  quizContainer.style.display = 'block';
  initQuiz();
});

//종료 버튼
endQuizBtn.addEventListener('click', () => {
  // 마지막 문제에 대한 처리를 위해 체크 로직 추가
  if (currentQuestionIndex === wordList.length - 1) {
    checkAnswer(document.querySelector('button[type="button"]').textContent.split('. ')[1]);
  }

  endQuizBtn.style.display = 'none';
  showResult();
});

//셔플
function shuffleArray(array) {
  for (let i = array.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [array[i], array[j]] = [array[j], array[i]];
  }
}

function initQuiz() {
  shuffleArray(wordList);
  //초기화
  currentQuestionIndex = 0;
  attemptedQuestions = 0;
  displayQuestion();
}

//단어 생성
function displayQuestion() {
  buttonMaker();
  questionNumber.innerText = `# ${currentQuestionIndex + 1}`;
  if (questionLanguage === 'eng') {
    question.innerText = `${wordList[currentQuestionIndex].eng}\n다음 중 올바른 뜻을 선택하세요.`;
  } else {
    question.innerText = `${wordList[currentQuestionIndex].kor}\n다음 중 올바른 뜻을 선택하세요.`;
  }
  optionsContainer.style.display = 'block';
}

// 버튼 생성
function buttonMaker() {
  const shuffledAnswers = shuffleOptions(
    wordList[currentQuestionIndex][questionLanguage === 'eng' ? 'kor' : 'eng'],
    wordList
  );
  let buttonsHTML = '';
  shuffledAnswers.forEach((answer, index) => {
    buttonsHTML += `<button type="button" onclick="checkAnswer('${answer}')">${
      index + 1
    }. ${answer}</button>`;
  });

  optionsContainer.innerHTML = buttonsHTML;
}

//옵션을 셔플
function shuffleOptions(correctAnswer, allAnswers) {
  let incorrectAnswers = allAnswers
    .map((word) => (questionLanguage === 'eng' ? word.kor : word.eng))
    .filter((word) => word !== correctAnswer);
  let sortedOptions = [];
  //사지선다
  for (let i = 0; i < 3; i++) {
    const randomIndex = Math.floor(Math.random() * incorrectAnswers.length);
    sortedOptions.push(incorrectAnswers[randomIndex]);
    incorrectAnswers.splice(randomIndex, 1);
  }
  sortedOptions.push(correctAnswer);
  shuffleArray(sortedOptions);
  return sortedOptions;
}

// 다음 문제로 넘아가는 이벤트
function nextQuestion() {
  currentQuestionIndex++;
  if (currentQuestionIndex < wordList.length) {
    displayQuestion();
  } else {
    showResult();
  }
}

//체점 결과
function showResult() {
  optionsContainer.style.display = 'none';
  question.style.display = 'none';

  // attemptedQuestions 사용하여 정확한 계산 수행
  let resultPercentage = (score / attemptedQuestions) * 100;

  resultText.innerText = `${attemptedQuestions}문제 중에 ${score}개를 맞혔습니다. 점수는 ${resultPercentage.toFixed(
    2
  )}점 입니다.`;

  resultContainer.style.display = 'block';
}

//다시 시작 버튼 이벤트
restartBtn.addEventListener('click', () => {
  score = 0;
  wrongWords = []; // 틀린 단어 목록을 초기화
  resultContainer.style.display = 'none';
  question.style.display = '';
  endQuizBtn.style.display = '';
  initQuiz();
});

// '틀린 단어 보기' 버튼에 이벤트 리스너 추가
wrongWordBtn.addEventListener('click', showWrongWords);

// 정답 판별
function checkAnswer (answer) {
  attemptedQuestions++;
  if (
    answer ===
    (questionLanguage === 'eng'
      ? wordList[currentQuestionIndex].kor
      : wordList[currentQuestionIndex].eng)
  ) {
    score++
    nextQuestion()
  } else {
    // 틀린 단어를 wrongWords 배열에 추가하는 로직
    wrongWords.push(wordList[currentQuestionIndex]);


    let answerDisplay = document.createElement('div')
    answerDisplay.setAttribute('id', 'answer-display')
    answerDisplay.innerText = `오답! 정답은: ${
      questionLanguage === 'eng'
        ? wordList[currentQuestionIndex].kor
        : wordList[currentQuestionIndex].eng
    }`

    optionsContainer.style.display = 'none'
    question.appendChild(answerDisplay)

    let nextButton = document.createElement('button')
    nextButton.innerText = '다음 문제'
    
    nextButton.addEventListener('click', () => {
      nextQuestion()
    })

    question.appendChild(nextButton)
  }
}

// 틀린 단어 보기 함수
function showWrongWords() {
  let wrongWordsList = wrongWords.map(word => `${word.eng} : ${word.kor}`).join('<br>');
  if (wrongWordsList.length == 0) {
    resultText.innerHTML = `틀린 단어가 없습니다!`;
  } else {
    resultText.innerHTML = `<br>${wrongWordsList}`;
  }
  resultContainer.style.display = 'block';
}

function showQuestion() {
  if (document.getElementById('answer-display')) {
    question.removeChild(document.getElementById('answer-display'));
  }

  optionsContainer.style.display = 'block';
  displayQuestion();
}
initQuiz();
